/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ptik;

import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author SAMSUNG
 */
public class FormTiketMySql extends javax.swing.JFrame {

    private final CRUDMySql crud = new CRUDMySql();
    private final DefaultTableModel model = new DefaultTableModel();
    private String status;
    private PemesananTiket pt;

    /**
     * Creates new form FormTiketSQLite
     */
    public FormTiketMySql() {
        initComponents();
        kolomTabel();
        getAllData();
    }

    private void kolomTabel() {
        model.addColumn("ID");
        model.addColumn("Nama Pemesan");
        model.addColumn("No Telepon");
        model.addColumn("Kereta");
        model.addColumn("Kelas");
        model.addColumn("Stasiun Asal");
        model.addColumn("Stasiun Tujuan");
        model.addColumn("Tanggal Berangkat");
        model.addColumn("Jam Berangkat");
        model.addColumn("Harga");
        tblKereta.setModel(model);
    }

    private void getAllData() {
        try {
            model.setRowCount(0);
            crud.bukaKoneksi();
            ArrayList<PemesananTiket> listPemesananTiket = crud.read();
            System.out.println(listPemesananTiket.size());
            for (PemesananTiket pt : listPemesananTiket) {
                model.addRow(new Object[]{
                    pt.getId(),
                    pt.getNamapemesan(),
                    pt.getTelp(),
                    pt.getNamakereta(),
                    pt.getKelas(),
                    pt.getStasiunasal(),
                    pt.getStasiuntujuan(),
                    pt.getTglberangkat(),
                    pt.getJamberangkat(),
                    pt.getHarga()
                });
            }
            crud.tutupKoneksi();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Gagal Mengambil Data");
        }
    }

    private void editData() {
        if (status.equals("add")) {
            txtId.setText("");
            txtNamaPemesan.setText("");
            txtTelp.setText("");
            txtKereta.setText("");
            txtKelas.setText("");
            txtAsal.setText("");
            txtTujuan.setText("");
            txtTgl.setText("");
            txtJam.setText("");
            txtHarga.setText("");
        }
        txtId.setEditable(true);
        txtNamaPemesan.setEditable(true);
        txtTelp.setEditable(true);
        txtKereta.setEditable(true);
        txtKelas.setEditable(true);
        txtAsal.setEditable(true);
        txtTujuan.setEditable(true);
        txtTgl.setEditable(true);
        txtJam.setEditable(true);
        txtHarga.setEditable(true);
        btSimpan.setEnabled(true);
        btBatal.setEnabled(true);
        btTambah.setEnabled(false);
        btUbah.setEnabled(false);
        btHapus.setEnabled(false);
        btKeluar.setEnabled(false);
        txtNamaPemesan.requestFocus();
    }

    private void readData() {
        txtId.setEditable(false);
        txtNamaPemesan.setEditable(false);
        txtTelp.setEditable(false);
        txtKereta.setEditable(false);
        txtKelas.setEditable(false);
        txtAsal.setEditable(false);
        txtTujuan.setEditable(false);
        txtTgl.setEditable(false);
        txtJam.setEditable(false);
        txtHarga.setEditable(false);
        btSimpan.setEnabled(false);
        btBatal.setEnabled(false);
        btTambah.setEnabled(true);
        btUbah.setEnabled(true);
        btHapus.setEnabled(true);
        btKeluar.setEnabled(true);
    }

    private void kosongkanTeks() {
        txtId.setText("");
        txtNamaPemesan.setText("");
        txtTelp.setText("");
        txtKereta.setText("");
        txtKelas.setText("");
        txtAsal.setText("");
        txtTujuan.setText("");
        txtTgl.setText("");
        txtJam.setText("");
        txtHarga.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNamaPemesan = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        txtKereta = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        txtAsal = new javax.swing.JTextField();
        txtTujuan = new javax.swing.JTextField();
        txtTgl = new javax.swing.JTextField();
        txtJam = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKereta = new javax.swing.JTable();
        btSimpan = new javax.swing.JButton();
        btBatal = new javax.swing.JButton();
        btTambah = new javax.swing.JButton();
        btUbah = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btKeluar = new javax.swing.JButton();
        btFormSQLite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("DATA PEMESANAN TIKET");

        jLabel2.setText("ID");

        jLabel3.setText("Nama Pemesan");

        jLabel4.setText("Telp");

        jLabel5.setText("Kereta");

        jLabel6.setText("Kelas");

        jLabel7.setText("Stasiun Asal");

        jLabel8.setText("Stasiun Tujuan");

        jLabel9.setText("Tanggal Berangkat");

        jLabel10.setText("Jam Berangkat");

        jLabel11.setText("Harga");

        txtId.setEditable(false);

        txtNamaPemesan.setEditable(false);

        txtTelp.setEditable(false);

        txtKereta.setEditable(false);

        txtKelas.setEditable(false);

        txtAsal.setEditable(false);

        txtTujuan.setEditable(false);

        txtTgl.setEditable(false);

        txtJam.setEditable(false);

        txtHarga.setEditable(false);

        tblKereta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKereta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKeretaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKereta);

        btSimpan.setText("Simpan");
        btSimpan.setEnabled(false);
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        btBatal.setText("Batal");
        btBatal.setEnabled(false);
        btBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatalActionPerformed(evt);
            }
        });

        btTambah.setText("Tambah");
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });

        btUbah.setText("Ubah");
        btUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUbahActionPerformed(evt);
            }
        });

        btHapus.setText("Hapus");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        btKeluar.setText("Keluar");
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });

        btFormSQLite.setText("Form SQLite");
        btFormSQLite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFormSQLiteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtKereta, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                            .addComponent(txtKelas)
                                            .addComponent(txtAsal)
                                            .addComponent(txtTujuan)
                                            .addComponent(txtTgl)
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtJam, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHarga))
                                        .addGap(29, 29, 29)))
                                .addComponent(btSimpan)
                                .addGap(26, 26, 26)
                                .addComponent(btBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(txtNamaPemesan))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btTambah)
                                .addGap(34, 34, 34)
                                .addComponent(btUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btFormSQLite)
                                .addGap(18, 18, 18)
                                .addComponent(btKeluar)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSimpan)
                    .addComponent(btBatal))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTambah)
                    .addComponent(btUbah)
                    .addComponent(btHapus)
                    .addComponent(btKeluar)
                    .addComponent(btFormSQLite))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed
        readData();
    }//GEN-LAST:event_btBatalActionPerformed

    private void btUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUbahActionPerformed
        status = "edit";
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih data dahulu");
        } else {
            editData();
        }
    }//GEN-LAST:event_btUbahActionPerformed

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        status = "add";
        editData();
    }//GEN-LAST:event_btTambahActionPerformed

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
         PemesananTiket pemesananTiket;
        if (status.equals("add")) {
            try {
                if (txtNamaPemesan.getText().isEmpty() || txtTelp.getText().isEmpty() || txtKereta.getText().isEmpty() || txtKelas.getText().isEmpty() || txtAsal.getText().isEmpty() || txtTujuan.getText().isEmpty() || txtTgl.getText().isEmpty() || txtJam.getText().isEmpty() || txtHarga.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Data harus diisi semua");
                } else {
                    crud.bukaKoneksi();
                    pemesananTiket = new PemesananTiket();
                    pemesananTiket.setNamapemesan(txtNamaPemesan.getText());
                    pemesananTiket.setTelp(txtTelp.getText());
                    pemesananTiket.setNamakereta(txtKereta.getText());
                    pemesananTiket.setKelas(txtKelas.getText());
                    pemesananTiket.setStasiunasal(txtAsal.getText());
                    pemesananTiket.setStasiuntujuan(txtTujuan.getText());
                    pemesananTiket.setTglberangkat(txtTgl.getText());
                    pemesananTiket.setJamberangkat(txtJam.getText());
                    pemesananTiket.setHarga(Integer.parseInt(txtHarga.getText()));
                    crud.create(pemesananTiket);
                    getAllData();
                    readData();
                    crud.tutupKoneksi();
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                }
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal disimpan");
            }
        } else {
            try {
                if (txtNamaPemesan.getText().isEmpty() || txtTelp.getText().isEmpty() || txtKereta.getText().isEmpty() || txtKelas.getText().isEmpty() || txtAsal.getText().isEmpty() || txtTujuan.getText().isEmpty() || txtTgl.getText().isEmpty() || txtJam.getText().isEmpty() || txtHarga.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Data harus diisi semua");
                } else {
                    crud.bukaKoneksi();
                    pemesananTiket = new PemesananTiket();
                    pemesananTiket.setId(Integer.parseInt(txtId.getText()));
                    pemesananTiket.setNamapemesan(txtNamaPemesan.getText());
                    pemesananTiket.setTelp(txtTelp.getText());
                    pemesananTiket.setNamakereta(txtKereta.getText());
                    pemesananTiket.setKelas(txtKelas.getText());
                    pemesananTiket.setStasiunasal(txtAsal.getText());
                    pemesananTiket.setStasiuntujuan(txtTujuan.getText());
                    pemesananTiket.setTglberangkat(txtTgl.getText());
                    pemesananTiket.setJamberangkat(txtJam.getText());
                    pemesananTiket.setHarga(Integer.parseInt(txtHarga.getText()));
                    crud.update(pemesananTiket);
                    getAllData();
                    readData();
                    crud.tutupKoneksi();
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                }
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal disimpan");
            }
        }
    }//GEN-LAST:event_btSimpanActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        if (pt == null) {
            JOptionPane.showMessageDialog(null, "Pilih data dahulu");
        } else {
            try {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(null, "Hapus data?", "Warning", dialogButton);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    crud.bukaKoneksi();
                    crud.delete(pt);
                    getAllData();
                    crud.tutupKoneksi();
                    pt = null;
                    kosongkanTeks();
                }
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Hapus data gagal");
            }
        }
    }//GEN-LAST:event_btHapusActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btKeluarActionPerformed

    private void tblKeretaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKeretaMouseClicked
        try {
            // TODO add your handling code here:
            int baris = tblKereta.getSelectedRow();
            crud.bukaKoneksi();
            pt = crud.readById(Integer.parseInt(tblKereta.getValueAt(baris, 0).toString()));
            crud.tutupKoneksi();
            txtId.setText(Integer.toString(pt.getId()));
            txtNamaPemesan.setText(pt.getNamapemesan());
            txtTelp.setText(pt.getTelp());
            txtKereta.setText(pt.getNamakereta());
            txtKelas.setText(pt.getKelas());
            txtAsal.setText(pt.getStasiunasal());
            txtTujuan.setText(pt.getStasiuntujuan());
            txtTgl.setText(pt.getTglberangkat());
            txtJam.setText(pt.getJamberangkat());
            txtHarga.setText(Integer.toString(pt.getHarga()));
 
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Ambil data gagal");
        }
    }//GEN-LAST:event_tblKeretaMouseClicked

    private void btFormSQLiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFormSQLiteActionPerformed
        this.setVisible(false);
        new FormTiketSQLite().setVisible(true);
    }//GEN-LAST:event_btFormSQLiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTiketSQLite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTiketSQLite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTiketSQLite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTiketSQLite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTiketSQLite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btFormSQLite;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKereta;
    private javax.swing.JTextField txtAsal;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtKereta;
    private javax.swing.JTextField txtNamaPemesan;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtTgl;
    private javax.swing.JTextField txtTujuan;
    // End of variables declaration//GEN-END:variables
}
